### ISSUE TITLE
Using in connection with own Nextcloud-Instance

### ISSUE THREAD

**Issue by dominikponniah** [Infomaniak/android-kDrive#39]
It seems like the basic backend from kDrive is based on some ownCloud-Stuff. Is there any possibility to change the Server-Access from the kDrive-System to my own Nextcloud-Instance?

**Comment by alxschilling** [comment]
The kDrive backend has never been a Nextcloud or Owncloud fork. It is a 100% home made back-end. Our backend provides a REST API and a WEBDAV API.
For our old mobile application, we used WebDav, which is no longer the case today (we now use Rest API calls). So unfortunately it is not possible to connect your own nexcloud server to our new mobile application.
On the other hand, the reverse is possible, you can use kDrive with your Nextcloud app, because our backend is compatible with WebDav.
