### ISSUE TITLE
Blink folder when move lot of files

### ISSUE THREAD

**Issue by JorisBodin** [Infomaniak/android-kDrive#897]

**Comment by FabianDevel** [comment]
The folder is blinking because the realm adapter ([](https://github.com/realm/realm-android-adapters/blob/master/adapters/src/main/java/io/realm/RealmRecyclerViewAdapter.java)) notify the recycler view when the children of the object are modified.  Thus each time a file is deleted or added to a folder, this folder is considered modified and bound again.

The solution would be to write our own RealmRecyclerViewAdapter, which will be done later when upgrading to realm-kotlin.
